variables:
  LC_ALL: C

before_script:
 - docker info
 - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.labs.nic.cz

stages:
  - python3

build_image_python3:
  image: docker:git
  stage: python3
  services:
    - docker:dind
  script:
    - docker build -t registry.labs.nic.cz/turris/foris-ci/python3 .
    - docker push registry.labs.nic.cz/turris/foris-ci/python3
  tags:
    - dind
  only:
    - master
