variables:
  LC_ALL: C

before_script:
 - docker info
 - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.nic.cz

stages:
  - build
  - push

build_image_python3:
  image: docker:git
  stage: build
  services:
    - docker:dind
  script:
    - docker build -t registry.nic.cz/turris/foris-ci/base -f base/Dockerfile base
    - docker build -t registry.nic.cz/turris/foris-ci/python3 -t registry.nic.cz/turris/foris-ci/ci-tests -f ci-tests/Dockerfile ci-tests
    - docker build -t registry.nic.cz/turris/foris-ci/supervised -f supervised/Dockerfile supervised
    - docker build -t registry.nic.cz/turris/foris-ci/foris-controller-mock -f foris-controller-mock/Dockerfile foris-controller-mock
    - docker build -t registry.nic.cz/turris/foris-ci/reforis-demo -f reforis-demo/Dockerfile reforis-demo
  tags:
    - dind
  only:
    - master

push_image_python3:
  image: docker:git
  stage: push
  services:
    - docker:dind
  script:
    - docker push registry.nic.cz/turris/foris-ci/python3
    - docker push registry.nic.cz/turris/foris-ci/base
    - docker push registry.nic.cz/turris/foris-ci/python3
    - docker push registry.nic.cz/turris/foris-ci/ci-tests
    - docker push registry.nic.cz/turris/foris-ci/supervised
    - docker push registry.nic.cz/turris/foris-ci/foris-controller-mock
    - docker push registry.nic.cz/turris/foris-ci/reforis-demo
  tags:
    - dind
  only:
    - master
