variables:
  LC_ALL: C

before_script:
 - docker info
 - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.nic.cz

stages:
  - base
  - supervised
  - ci-tests
  - foris-controller-mock
  - reforis-demo

image::base:
  image: docker:git
  stage: base
  services:
    - docker:dind
  script:
    - docker build -t registry.nic.cz/turris/foris-ci/base -f base/Dockerfile base
    - docker push registry.nic.cz/turris/foris-ci/base
  tags:
    - dind
  only:
    - master


image::supervised:
  image: docker:git
  stage: supervised
  needs: ["image::base"]
  services:
    - docker:dind
  script:
    - docker pull registry.nic.cz/turris/foris-ci/base
    - docker build -t registry.nic.cz/turris/foris-ci/supervised -f supervised/Dockerfile supervised
    - docker push registry.nic.cz/turris/foris-ci/supervised
  tags:
    - dind
  only:
    - master

image::ci-tests:
  image: docker:git
  stage: ci-tests
  needs: ["image::base"]
  services:
    - docker:dind
  script:
    - docker pull registry.nic.cz/turris/foris-ci/base
    - docker build -t registry.nic.cz/turris/foris-ci/python3 -t registry.nic.cz/turris/foris-ci/ci-tests -f ci-tests/Dockerfile ci-tests
    - docker push registry.nic.cz/turris/foris-ci/python3
    - docker push registry.nic.cz/turris/foris-ci/ci-tests
  tags:
    - dind
  only:
    - master

image::foris-controller-mock:
  image: docker:git
  stage: foris-controller-mock
  needs: ["image::supervised"]
  services:
    - docker:dind
  script:
    - docker pull registry.nic.cz/turris/foris-ci/supervised
    - docker build -t registry.nic.cz/turris/foris-ci/foris-controller-mock -f foris-controller-mock/Dockerfile foris-controller-mock
    - docker push registry.nic.cz/turris/foris-ci/foris-controller-mock
  tags:
    - dind
  only:
    - master

image::reforis-demo:
  image: docker:git
  stage: reforis-demo
  needs: ["image::foris-controller-mock"]
  services:
    - docker:dind
  script:
    - docker pull registry.nic.cz/turris/foris-ci/foris-controller-mock
    - docker build -t registry.nic.cz/turris/foris-ci/reforis-demo -f reforis-demo/Dockerfile reforis-demo
    - docker push registry.nic.cz/turris/foris-ci/reforis-demo
  tags:
    - dind
  only:
    - master
