variables:
  LC_ALL: C

before_script:
 - docker info
 - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.nic.cz

stages:
  - build
  - push

build_image_python3:
  image: docker:git
  stage: build
  services:
    - docker:dind
  script:
    - docker build -t registry.nic.cz/turris/foris-ci/python3 .
  tags:
    - dind

push_image_python3:
  image: docker:git
  stage: push
  services:
    - docker:dind
  script:
    - docker push registry.nic.cz/turris/foris-ci/python3
  tags:
    - dind
  only:
    - master
